//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JonProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int FotoId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PostId { get; set; }
        public System.DateTime UploadDate { get; set; }
        public byte[] FotoArchivo { get; set; }
        public string FotoTipo { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
